# Generated by Django 3.0.5 on 2021-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=30)),
                ('insurance_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_price',
            field=models.IntegerField(default=0),
        ),
    ]
