# Generated by Django 3.0.5 on 2021-01-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210111_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='insurance_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
